version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    networks:
      - wafnet
    restart: unless-stopped

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    ports:
      - "80:8080"
    environment:
      - BACKEND=http://dvwa:80
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
    depends_on:
      - dvwa
    networks:
      - wafnet

networks:
  wafnet:
    driver: bridge